import Head from "next/head";
import { Inter } from "@next/font/google";
import { motion as m } from "framer-motion";
import { container, item } from "../animation";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <m.div
      initial={{ y: "100%" }}
      animate={{ y: "0%" }}
      transition={{ duration: 0.75, ease: "easeOut" }}
      exit={{ opacity: 1 }}
      className="text-gray-900 absolute top-0 left-0 w-full h-full bg-orange-200 lg:px-48 px-16"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="my-60 p-1 overflow-hidden">
          <m.h1
            animate={{ y: 0 }}
            initial={{ y: "100%" }}
            transition={{ delay: 0.5, duration: 0.5 }}
            className="text-6xl text-center lg:text-right lg:text-9xl"
          >
            Hellooo!
          </m.h1>
        </div>
        <div className="flex justify-between">
          <div>
            <h2>Nafis</h2>
            <h2>Nihal</h2>
            <h2>2023</h2>
          </div>
          <m.div variants={container} initial="hidden" animate="show">
            <div className="overflow-hidden">
              <m.div variants={item}>
                <h3>Bla bla should not be discovered</h3>
              </m.div>
            </div>
            <div className="overflow-hidden">
              <m.div variants={item}>
                <h3>We should not think about aliens</h3>
              </m.div>
            </div>
            <div className="overflow-hidden">
              <m.div variants={item}>
                <h3>You can see cool things here</h3>
              </m.div>
            </div>
          </m.div>
        </div>
      </main>
    </m.div>
  );
}
